[alias]
lcov = [
  "llvm-cov",
  "--locked",
  "--all-features",
  "--workspace",
  "--no-report",
  "nextest",
]
lcov-json = [
  "llvm-cov",
  "report",
  "--codecov",
  "--output-path",
  "cov.json",
  "--ignore-filename-regex",
  "cli/src/main",
]
lcov-assert = [
  "llvm-cov",
  "report",
  "--fail-under-functions",
  "80",
  "--fail-under-lines",
  "80",
  "--fail-under-file-lines",
  "80",
  "--fail-under-regions",
  "80",
  "--ignore-filename-regex",
  "cli/src/main",
]
ins-self = ["install", "--path", "crates/reportage-cli", "--locked"]
