name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: just
          locked: true
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-llvm-cov
          locked: true
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: just check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required for private repos or protected branches
          files: cov.json
          fail_ci_if_error: true
