name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Unit and Integration tests
    permissions:
      contents: read
      id-token: write # for codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: cargo-nextest
          locked: true
      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: just
          locked: true
      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: cargo-llvm-cov
          locked: true
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Check
        run: just check

      - name: Check grammar documentation
        run: just lang-docs-check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ always() }}
        with:
          files: cov.json
          fail_ci_if_error: true
          use_oidc: true

  setup-artifacts:
    uses: ./.github/workflows/_setup_artifacts.yml

  assert-archive:
    name: Assert archive
    runs-on: ubuntu-latest
    needs: setup-artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: just
          locked: true
      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: toml-cli
          locked: true

      - name: Get Archive
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.setup-artifacts.outputs.artifact_name }}
          path: dist
      - name: Get current version
        id: get-version
        run: echo "version=$(just get-version)" >> $GITHUB_OUTPUT

      - name: assert artifacts
        uses: tooppoo/fs-assert-action@latest
        with:
          root: dist
          manifest: |
            version: 1
            subjects:
              - path: checksums.txt
                assertions:
                  - exists
                  - is_regular_file
                  - line_count:
                      equals: 2
              - path: reportage_${{ steps.get-version.outputs.version }}_Linux_x86_64.tar.gz
                assertions:
                  - exists
                  - is_regular_file
                  - is_tarball
              - path: reportage_${{ steps.get-version.outputs.version }}_Linux_aarch64.tar.gz
                assertions:
                  - exists
                  - is_regular_file
                  - is_tarball

      - name: extract archives
        run: |
          tar -xzvf dist/reportage_${{ steps.get-version.outputs.version }}_Linux_x86_64.tar.gz
          tar -xzvf dist/reportage_${{ steps.get-version.outputs.version }}_Linux_aarch64.tar.gz
          find ./dist # debug

      - name: assert extracted files
        uses: tooppoo/fs-assert-action@latest
        with:
          root: dist
          manifest: |
            version: 1
            subjects:
              - path: reportage_${{ steps.get-version.outputs.version }}_Linux_x86_64/reportage
                assertions:
                  - exists
                  - is_regular_file
                  - is_executable
              - path: reportage_${{ steps.get-version.outputs.version }}_Linux_aarch64/reportage
                assertions:
                  - exists
                  - is_regular_file
                  - is_executable

  smoke-test:
    name: Smoke test for ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: x86_64
            runner: ubuntu-24.04
          - name: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    needs: setup-artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: just
          locked: true
      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: toml-cli
          locked: true

      - name: Get Archive
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.setup-artifacts.outputs.artifact_name }}
          path: dist

      - name: Extract archive
        run: |
          find ./dist # debug
          target="reportage_${{ needs.setup-artifacts.outputs.version }}_Linux_${{ matrix.name }}"
          tar -xzvf "./dist/${target}.tar.gz"
          cp "dist/${target}/reportage" ../bin/reportage

      - name: run smoke test
        run: ./bin/reportage --help

  e2e:
    name: E2E(self testing)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: just
          locked: true

      - name: Install Reportage
        run: just self-install

      - name: Run E2E
        run: reportage

  examples:
    name: Run examples actually
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: just
          locked: true

      - name: Install Reportage
        run: just self-install

      - name: Run Examples
        run: reportage --config reportage.examples.kdl
